"""Created Term table

Revision ID: 79c5b9b41426
Revises: 92378f22eaca
Create Date: 2024-06-14 04:23:27.213420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '79c5b9b41426'
down_revision: Union[str, None] = '92378f22eaca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term_tbl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('term_number', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term_course_tbl',
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course_tbl.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term_tbl.id'], )
    )
    op.add_column('enrollment_tbl', sa.Column('term_id', sa.Integer(), nullable=False))
    op.add_column('enrollment_tbl', sa.Column('status', sa.Enum('IN_PROGRESS', 'PASSED', 'FAILED', name='coursestatus'), nullable=False))
    op.add_column('enrollment_tbl', sa.Column('score', sa.Integer(), nullable=True))
    op.drop_constraint('enrollment_tbl_ibfk_2', 'enrollment_tbl', type_='foreignkey')
    op.drop_constraint('enrollment_tbl_ibfk_3', 'enrollment_tbl', type_='foreignkey')
    op.create_foreign_key(None, 'enrollment_tbl', 'term_tbl', ['term_id'], ['id'])
    op.drop_column('enrollment_tbl', 'student_id')
    op.drop_column('enrollment_tbl', 'user_id')
    op.drop_column('user_tbl', 'term')
    op.drop_column('user_tbl', 'average_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tbl', sa.Column('average_score', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_tbl', sa.Column('term', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('enrollment_tbl', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('enrollment_tbl', sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'enrollment_tbl', type_='foreignkey')
    op.create_foreign_key('enrollment_tbl_ibfk_3', 'enrollment_tbl', 'user_tbl', ['user_id'], ['id'])
    op.create_foreign_key('enrollment_tbl_ibfk_2', 'enrollment_tbl', 'user_tbl', ['student_id'], ['id'])
    op.drop_column('enrollment_tbl', 'score')
    op.drop_column('enrollment_tbl', 'status')
    op.drop_column('enrollment_tbl', 'term_id')
    op.drop_table('term_course_tbl')
    op.drop_table('term_tbl')
    # ### end Alembic commands ###
