"""Creating other tables

Revision ID: 92378f22eaca
Revises: 7d30758bc31d
Create Date: 2024-06-13 07:12:35.247164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92378f22eaca'
down_revision: Union[str, None] = '7d30758bc31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tbl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('family', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female'), nullable=True),
    sa.Column('national_code', sa.String(length=20), nullable=False),
    sa.Column('birthday', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('term', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_code'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course_tbl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('unit_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['user_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollment_tbl',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_tbl.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user_tbl.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_tbl.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.create_table('prerequisite_tbl',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course_tbl.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['course_tbl.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prerequisite_tbl')
    op.drop_table('enrollment_tbl')
    op.drop_table('course_tbl')
    op.drop_table('user_tbl')
    # ### end Alembic commands ###
