"""Added StudentTerm, ProfessorTerm, Teaching tables

Revision ID: e7fcddb87a2a
Revises: 79c5b9b41426
Create Date: 2024-06-14 08:03:20.975721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e7fcddb87a2a'
down_revision: Union[str, None] = '79c5b9b41426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor_term_tbl',
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('average_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professor_tbl.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term_tbl.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professor_id', 'term_id', name='uix_student_term')
    )
    op.create_table('student_term_tbl',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'PASSED', 'FAILED', name='termstatus'), nullable=False),
    sa.Column('average_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_tbl.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term_tbl.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'term_id', name='uix_student_term')
    )
    op.create_table('teaching_tbl',
    sa.Column('professor_term_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_tbl.id'], ),
    sa.ForeignKeyConstraint(['professor_term_id'], ['professor_term_tbl.id'], ),
    sa.PrimaryKeyConstraint('professor_term_id', 'course_id')
    )
    op.drop_table('term_course_tbl')
    op.add_column('enrollment_tbl', sa.Column('student_term_id', sa.Integer(), nullable=False))
    op.drop_constraint('enrollment_tbl_ibfk_2', 'enrollment_tbl', type_='foreignkey')
    op.create_foreign_key(None, 'enrollment_tbl', 'student_term_tbl', ['student_term_id'], ['id'])
    op.drop_column('enrollment_tbl', 'term_id')
    op.add_column('term_tbl', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('term_tbl', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.drop_constraint('term_tbl_ibfk_1', 'term_tbl', type_='foreignkey')
    op.drop_column('term_tbl', 'average_score')
    op.drop_column('term_tbl', 'student_id')
    op.drop_column('term_tbl', 'term_number')
    op.drop_column('user_tbl', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tbl', sa.Column('type', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('term_tbl', sa.Column('term_number', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('term_tbl', sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('term_tbl', sa.Column('average_score', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('term_tbl_ibfk_1', 'term_tbl', 'user_tbl', ['student_id'], ['id'])
    op.drop_column('term_tbl', 'end_date')
    op.drop_column('term_tbl', 'start_date')
    op.add_column('enrollment_tbl', sa.Column('term_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'enrollment_tbl', type_='foreignkey')
    op.create_foreign_key('enrollment_tbl_ibfk_2', 'enrollment_tbl', 'term_tbl', ['term_id'], ['id'])
    op.drop_column('enrollment_tbl', 'student_term_id')
    op.create_table('term_course_tbl',
    sa.Column('term_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course_tbl.id'], name='term_course_tbl_ibfk_1'),
    sa.ForeignKeyConstraint(['term_id'], ['term_tbl.id'], name='term_course_tbl_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('teaching_tbl')
    op.drop_table('student_term_tbl')
    op.drop_table('professor_term_tbl')
    op.drop_table('student_tbl')
    op.drop_table('professor_tbl')
    op.drop_table('admin_tbl')
    # ### end Alembic commands ###
